### ISSUE TITLE
Docker DB fails to build on Mac M1

### ISSUE THREAD

**Issue by shakir12321** [openimis/openimis-db_dkr#11]
After using the env file available on https://github.com/openimis/openimis-dist_dkr, the docker-compose up -d fails with following error on DB side.

Unable to proceed with demo installation.

 => => extracting sha256:bb39fd5369da23b69cc29133c9410cf960cc78d2fb99cd21374e6c7217d25a3f                   0.1s
 => [ 2/19] RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gettext            4.1s
 => [ 3/19] RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -                      0.8s 
 => [ 4/19] RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/m  0.5s 
 => [ 5/19] RUN apt-get update                                                                              1.1s 
 => ERROR [ 6/19] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools                              0.6s 
------                                                                                                           
 > [ 6/19] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools:                                         
#9 0.180 Reading package lists...                                                                                
#9 0.515 Building dependency tree...                                                                             
#9 0.582 Reading state information...
#9 0.627 E: Unable to locate package msodbcsql17
#9 0.627 E: Unable to locate package mssql-tools
------
executor failed running [/bin/sh -c ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools]: exit code: 100
ERROR: Service 'backend' failed to build : Build failed
shakir (main) $ docker-compose up -d
WARNING: The OPENIMIS_BE_CONF_JSON variable is not set. Defaulting to a blank string.
WARNING: The OPENIMIS_FE_CONF_JSON variable is not set. Defaulting to a blank string.
Building backend
[+] Building 1.9s (8/21)                                                                                         
 => CACHED [internal] load git source https://github.com/openimis/openimis-be_py.git#main                   0.0s
 => [internal] load metadata for docker.io/library/python:3.8-buster                                        1.2s
 => [ 1/19] FROM docker.io/library/python:3.8-buster@sha256:96ffed996338ea3429c4d40db26ffc3be8cb1c1ae2d445  0.0s
 => CACHED [ 2/19] RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gettext     0.0s
 => CACHED [ 3/19] RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -               0.0s
 => CACHED [ 4/19] RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.l  0.0s
 => CACHED [ 5/19] RUN apt-get update                                                                       0.0s
 => ERROR [ 6/19] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools                              0.7s
------                                                                                                           
 > [ 6/19] RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools:                                         
#8 0.237 Reading package lists...                                                                                
#8 0.585 Building dependency tree...
#8 0.649 Reading state information...
#8 0.697 E: Unable to locate package msodbcsql17
#8 0.697 E: Unable to locate package mssql-tools
------
executor failed running [/bin/sh -c ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools]: exit code: 100
ERROR: Service 'backend' failed to build : Build failed

 (main) $

**Comment by dragos-dobre** [comment]
Can you please check solutions from https://stackoverflow.com/questions/49768683/unable-to-locate-package-msodbcsql ?

**Comment by shakir12321** [comment]
Looks like a bigger issue for Mac M1 chip, so switching to windows.

Here is the reference for others on similar issue. 

https://github.com/MicrosoftDocs/sql-docs/issues/6494

After much research, the reason I found out it was happening was because I am using a Mac with the new M1 chip and there are currently no msodbcsql17 or mssql-tools packages for arm64 architecture.

The solution was to change the base image as follows at the start of the Dockerfile:

FROM --platform=linux/amd64 python:3.8.6
This fixes the installation to the older AMD architecture. Obviously you can change the Python version to whatever version you have for oyur project.

All else being even after that, the image successfully builds. This has taken me ages to figure this out, so hopefully someone else will benefit from it.

Host OS: Mac OS Big Sur (11.5.1)

# Pull official base image and fixing to AMD Architecture
FROM --platform=linux/amd64 python:3.8.6

# Create and set the working directory
WORKDIR /usr/src/app/

# Prevents Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE 1

# Causes all output to stdout to be flushed immediately
ENV PYTHONUNBUFFERED 1

# Mark the image as trusted
ENV DOCKER_CONTENT_TRUST 1

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

# Updates packages list for the image
RUN apt-get update

# Installs transport HTTPS
RUN apt-get install -y curl apt-transport-https

# Retrieves packages from Microsoft
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Updates packages for the image
RUN apt-get update

# Installs SQL drivers and tools
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

# Installs MS SQL Tools
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools

# Adds paths to the $PATH environment variable within the .bash_profile and .bashrc files
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

# Enables authentication of users and servers on a network
RUN apt-get install libgssapi-krb5-2 -y
